### ISSUE TITLE
Publish release v0.4.0

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/ios-sdk#330]
- [x] Find-and-replace the version in `userAgent` prefixes (PR #331)
- [x] Temporarily make `userAgent` a required parameter (PR #331)
- [x] Rename `ConversationV1` to `ConversationV1Experimental` (including folders)
- [x] Rename `RelationshipExtractionV1` to `RelationshipExtractionV1Beta` (including folders)
- [x] Generate documentation for `gh-pages` branch
- [x] Fix any undocumented code (#345)
- [x] Merge the above changes
- [x] Run all tests to verify correctness
- [x] Update the change log.
- [x] Update the readme with information about the new services. (#346, #347, #348, #349, #350)
- [x] Create a tag/release for `v0.4`.

**Comment by glennrfisher** [comment]
### Text To Speech

```json
{
  "warnings": [
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/TextToSpeechV1\/Models\/SynthesisVoice.swift",
      "line": 38,
      "symbol": "US_Michael",
      "symbol_kind": "source.lang.swift.decl.enumelement",
      "warning": "undocumented"
    }
  ],
  "source_directory": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK"
}
```

### Relationship Extraction

```json
{
  "warnings": [
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/RelationshipExtractionV1Beta\/Models\/Relations.swift",
      "line": 81,
      "symbol": "RelatedMentions",
      "symbol_kind": "source.lang.swift.decl.struct",
      "warning": "undocumented"
    }
  ],
  "source_directory": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK"
}
```

### Document Converion

```json
{
  "warnings": [
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/DocumentConversionV1\/DocumentConversion.swift",
      "line": 219,
      "symbol": "AnswerUnits",
      "symbol_kind": "source.lang.swift.decl.enumelement",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/DocumentConversionV1\/DocumentConversion.swift",
      "line": 220,
      "symbol": "HTML",
      "symbol_kind": "source.lang.swift.decl.enumelement",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/DocumentConversionV1\/DocumentConversion.swift",
      "line": 221,
      "symbol": "Text",
      "symbol_kind": "source.lang.swift.decl.enumelement",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/DocumentConversionV1\/Models\/FileType.swift",
      "line": 23,
      "symbol": "HTML",
      "symbol_kind": "source.lang.swift.decl.enumelement",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/DocumentConversionV1\/Models\/FileType.swift",
      "line": 24,
      "symbol": "XML",
      "symbol_kind": "source.lang.swift.decl.enumelement",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/DocumentConversionV1\/Models\/FileType.swift",
      "line": 25,
      "symbol": "PDF",
      "symbol_kind": "source.lang.swift.decl.enumelement",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/DocumentConversionV1\/Models\/FileType.swift",
      "line": 26,
      "symbol": "MSWord",
      "symbol_kind": "source.lang.swift.decl.enumelement",
      "warning": "undocumented"
    }
  ],
  "source_directory": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK"
}
```

### Alchemy Language

```json
{
  "warnings": [
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/AlchemyLanguageV1\/Models\/SAORelation.swift",
      "line": 29,
      "symbol": "action",
      "symbol_kind": "source.lang.swift.decl.var.instance",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/AlchemyLanguageV1\/Models\/SAORelation.swift",
      "line": 30,
      "symbol": "sentence",
      "symbol_kind": "source.lang.swift.decl.var.instance",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/AlchemyLanguageV1\/Models\/SAORelation.swift",
      "line": 31,
      "symbol": "subject",
      "symbol_kind": "source.lang.swift.decl.var.instance",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/AlchemyLanguageV1\/Models\/SAORelation.swift",
      "line": 32,
      "symbol": "object",
      "symbol_kind": "source.lang.swift.decl.var.instance",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/AlchemyLanguageV1\/Models\/SAORelation.swift",
      "line": 48,
      "symbol": "text",
      "symbol_kind": "source.lang.swift.decl.var.instance",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/AlchemyLanguageV1\/Models\/SAORelation.swift",
      "line": 49,
      "symbol": "lemmatized",
      "symbol_kind": "source.lang.swift.decl.var.instance",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/AlchemyLanguageV1\/Models\/SAORelation.swift",
      "line": 50,
      "symbol": "verb",
      "symbol_kind": "source.lang.swift.decl.var.instance",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/AlchemyLanguageV1\/Models\/SAORelation.swift",
      "line": 63,
      "symbol": "text",
      "symbol_kind": "source.lang.swift.decl.var.instance",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/AlchemyLanguageV1\/Models\/SAORelation.swift",
      "line": 64,
      "symbol": "tense",
      "symbol_kind": "source.lang.swift.decl.var.instance",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/AlchemyLanguageV1\/Models\/SAORelation.swift",
      "line": 65,
      "symbol": "negated",
      "symbol_kind": "source.lang.swift.decl.var.instance",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/AlchemyLanguageV1\/Models\/SAORelation.swift",
      "line": 84,
      "symbol": "text",
      "symbol_kind": "source.lang.swift.decl.var.instance",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/AlchemyLanguageV1\/Models\/SAORelation.swift",
      "line": 85,
      "symbol": "sentiment",
      "symbol_kind": "source.lang.swift.decl.var.instance",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/AlchemyLanguageV1\/Models\/SAORelation.swift",
      "line": 86,
      "symbol": "entity",
      "symbol_kind": "source.lang.swift.decl.var.instance",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/AlchemyLanguageV1\/Models\/SAORelation.swift",
      "line": 100,
      "symbol": "text",
      "symbol_kind": "source.lang.swift.decl.var.instance",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/AlchemyLanguageV1\/Models\/SAORelation.swift",
      "line": 101,
      "symbol": "sentiment",
      "symbol_kind": "source.lang.swift.decl.var.instance",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/AlchemyLanguageV1\/Models\/SAORelation.swift",
      "line": 102,
      "symbol": "sentimentFromSubject",
      "symbol_kind": "source.lang.swift.decl.var.instance",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/AlchemyLanguageV1\/Models\/SAORelation.swift",
      "line": 103,
      "symbol": "entity",
      "symbol_kind": "source.lang.swift.decl.var.instance",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/AlchemyLanguageV1\/Models\/QueryParam.swift",
      "line": 23,
      "symbol": "Excluded",
      "symbol_kind": "source.lang.swift.decl.enumelement",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/AlchemyLanguageV1\/Models\/QueryParam.swift",
      "line": 23,
      "symbol": "Included",
      "symbol_kind": "source.lang.swift.decl.enumelement",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/AlchemyLanguageV1\/Models\/DocumentEmotion.swift",
      "line": 20,
      "symbol": "DocumentEmotion",
      "symbol_kind": "source.lang.swift.decl.struct",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/AlchemyLanguageV1\/Models\/DocumentEmotion.swift",
      "line": 22,
      "symbol": "url",
      "symbol_kind": "source.lang.swift.decl.var.instance",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/AlchemyLanguageV1\/Models\/DocumentEmotion.swift",
      "line": 23,
      "symbol": "totalTransactions",
      "symbol_kind": "source.lang.swift.decl.var.instance",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/AlchemyLanguageV1\/Models\/DocumentEmotion.swift",
      "line": 24,
      "symbol": "language",
      "symbol_kind": "source.lang.swift.decl.var.instance",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/AlchemyLanguageV1\/Models\/DocumentEmotion.swift",
      "line": 25,
      "symbol": "docEmotions",
      "symbol_kind": "source.lang.swift.decl.var.instance",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/AlchemyLanguageV1\/Models\/DocumentEmotion.swift",
      "line": 27,
      "symbol": "init(json:)",
      "symbol_kind": "source.lang.swift.decl.function.method.instance",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/AlchemyLanguageV1\/Models\/Language.swift",
      "line": 37,
      "symbol": "ethnologue",
      "symbol_kind": "source.lang.swift.decl.var.instance",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/AlchemyLanguageV1\/Models\/Language.swift",
      "line": 40,
      "symbol": "iso6391",
      "symbol_kind": "source.lang.swift.decl.var.instance",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/AlchemyLanguageV1\/Models\/Entity.swift",
      "line": 47,
      "symbol": "init(json:)",
      "symbol_kind": "source.lang.swift.decl.function.method.instance",
      "warning": "undocumented"
    }
  ],
  "source_directory": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK"
}
```

### Alchemy Data News

```json
{
  "warnings": [
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/AlchemyDataNewsV1\/Models\/NewsResponse.swift",
      "line": 35,
      "symbol": "init(json:)",
      "symbol_kind": "source.lang.swift.decl.function.method.instance",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/AlchemyDataNewsV1\/Models\/Entity.swift",
      "line": 47,
      "symbol": "init(json:)",
      "symbol_kind": "source.lang.swift.decl.function.method.instance",
      "warning": "undocumented"
    },
    {
      "file": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK\/Source\/AlchemyDataNewsV1\/Models\/DocumentSource.swift",
      "line": 33,
      "symbol": "init(json:)",
      "symbol_kind": "source.lang.swift.decl.function.method.instance",
      "warning": "undocumented"
    }
  ],
  "source_directory": "\/Users\/glennfisher\/MIL\/Repositories\/Watson iOS SDK"
}
```

**Comment by glennrfisher** [comment]
All tests pass except for the three listed below. We think these tests were affected by changes to the services. These test failures have been noted with @germanattanasio.

- DialogV1Tests: `testGetConversationHistoryWithLimit()`
- LanguageTranslatorV2Tests: `testDeleteUnauthorized()`
- LanguageTranslatorV2Tests: `testDeleteNotFound()`

**Comment by glennrfisher** [comment]
Some issues were marked completed, but will be tracked in separate issues and completed with a v0.4.1 release.
